Repository Rollczi/LiteCommands, pull requests merged in 2023-10, with the labels that each got.

#228 GH-228 Update the list of projects using litecommands.
  README.md
Labels: documentation

#237 GH-223 Fix root command children appender and add unit test related to this case. Release 3.0.0-BETA-pre23
  README.md
  buildSrc/src/main/kotlin/litecommands-publish.gradle.kts
  examples/bukkit-adventure-platform/build.gradle.kts
  examples/bukkit-chatgpt/build.gradle.kts
  examples/bukkit/build.gradle.kts
  examples/velocity/build.gradle.kts
  litecommands-annotations/test/dev/rollczi/litecommands/annotations/route/RootCommandTest.java
  litecommands-core/src/dev/rollczi/litecommands/command/builder/CommandBuilderBase.java
  litecommands-core/src/dev/rollczi/litecommands/command/builder/CommandBuilderChildrenBase.java
  litecommands-core/src/dev/rollczi/litecommands/command/builder/CommandBuilderRootImpl.java
  litecommands-core/src/dev/rollczi/litecommands/input/raw/RawCommand.java
  litecommands-unit/src/dev/rollczi/litecommands/unit/TestPlatform.java
Labels: bug, hacktoberfest

#251 GH-221 Add Enum argument resolver
  litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/resolver/standard/EnumArgumentTest.java
  litecommands-core/src/dev/rollczi/litecommands/argument/parser/EmptyParserSetImpl.java
  litecommands-core/src/dev/rollczi/litecommands/argument/parser/ParserRegistryImpl.java
  litecommands-core/src/dev/rollczi/litecommands/argument/parser/ParserSetImpl.java
  litecommands-core/src/dev/rollczi/litecommands/argument/resolver/standard/EnumArgumentResolver.java
  litecommands-core/src/dev/rollczi/litecommands/argument/suggester/SuggesterRegistryImpl.java
  litecommands-core/test/dev/rollczi/litecommands/argument/parser/ParserRegistryImplTest.java
  litecommands-core/test/dev/rollczi/litecommands/argument/suggester/SuggesterRegistryImplTest.java
  litecommands-framework/src/dev/rollczi/litecommands/LiteCommandsFactory.java
  litecommands-unit/src/dev/rollczi/litecommands/unit/AssertSuggest.java
Labels: feature, hacktoberfest, hacktoberfest-accepted

#252 GH-233 Add Instant argument support
  litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/resolver/standard/InstantArgumentTest.java
  litecommands-core/src/dev/rollczi/litecommands/argument/resolver/standard/InstantArgumentResolver.java
  litecommands-core/src/dev/rollczi/litecommands/input/raw/RawInput.java
  litecommands-core/src/dev/rollczi/litecommands/message/LiteMessages.java
  litecommands-framework/src/dev/rollczi/litecommands/LiteCommandsFactory.java
  litecommands-unit/src/dev/rollczi/litecommands/unit/AssertSuggest.java
Labels: feature, hacktoberfest, hacktoberfest-accepted

#264 GH-263 Add API for requirements validators in command processing pipeline.
  examples/bukkit/src/main/java/dev/rollczi/example/bukkit/ExamplePlugin.java
  examples/bukkit/src/main/java/dev/rollczi/example/bukkit/command/FlyCommand.java
  examples/bukkit/src/main/java/dev/rollczi/example/bukkit/validator/IsNotOp.java
  examples/bukkit/src/main/java/dev/rollczi/example/bukkit/validator/IsNotOpValidator.java
  litecommands-annotations/src/dev/rollczi/litecommands/annotations/validator/requirment/AnnotatedValidator.java
  litecommands-annotations/src/dev/rollczi/litecommands/annotations/validator/requirment/AnnotatedValidatorProcessor.java
  litecommands-annotations/src/dev/rollczi/litecommands/annotations/validator/requirment/RequirementAnnotatedValidatorImpl.java
  litecommands-annotations/test/dev/rollczi/litecommands/annotations/LiteTestSpec.java
  litecommands-annotations/test/dev/rollczi/litecommands/annotations/validator/requirment/AnnotatedValidatorTest.java
  litecommands-core/src/dev/rollczi/litecommands/argument/parser/ParseResult.java
  litecommands-core/src/dev/rollczi/litecommands/command/executor/CommandExecuteService.java
  litecommands-core/src/dev/rollczi/litecommands/context/ContextResult.java
  litecommands-core/src/dev/rollczi/litecommands/meta/Meta.java
  litecommands-core/src/dev/rollczi/litecommands/requirement/RequirementResult.java
  litecommands-core/src/dev/rollczi/litecommands/validator/ValidatorResult.java
  litecommands-core/src/dev/rollczi/litecommands/validator/requirment/RequirementValidator.java
  litecommands-framework/src/dev/rollczi/litecommands/extension/annotations/LiteAnnotationsProcessorExtension.java
Labels: feature, API, hacktoberfest
